### ISSUE TITLE
reserves lot of space around the icons

### ISSUE THREAD

**Issue by prazjain** [jd-alexander/LikeButton#7]
Hi jd-alexander,
I like it, but it reserves way too much space around the icons.
Is there a way I can reduce the space around the icons, it just means that the dots will not travel as further before exploding.
Or is there a way to do that already?
My current icon size is 25dp, but it reserves space around 50dp or more.

Thanks
Prashant

**Comment by jd-alexander** [comment]
Yeah I calculate the space to display the animation by 3x the size of the button in question. I didnt create a way for the developer to change this though because they are several other values that rely on the size such as the dots and such so I didn't want to go through all the work to do that. I think you can use some form of  positioning tricks where your icons are being placed so that other elements can somewhat overlay the extra space and not impact the animation

**Comment by prazjain** [comment]
I am adding this button in a recycler view, and it is making the item
height way too much high.
Is there a quick way to make the animation size to be 1x, 1.5x, 2x etc?
Can you make that bit configurable? like shootingDotsHeight

I think that will be helpful.
Without that, no matter how much i like it, i just cannot use it in my
recyclerview :(

Thanks

**Comment by jd-alexander** [comment]
Okay I am going to add that change soon.

**Comment by jd-alexander** [comment]
This is the best I could do for now. You can manually set the size of the dots using the scale factor attribute . Will optimize it later. See docs  https://github.com/jd-alexander/LikeButton#animation-size

**Comment by prazjain** [comment]
Thanks JD, this looks much better.

**Comment by jd-alexander** [comment]
:+1:
